site_name: Fablab Skanderborg
site_url: https://fablabskanderborg.dk

# Markdown Extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  language: da
  logo: assets/fablab-logo-black-on-transparent.png
  features:
    #- navigation.instant
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Skift til lyst tema
      primary: teal
      accent: deep orange
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Skift til mørkt tema
      primary: teal
      accent: deep orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Skift til system standard
      primary: teal
      accent: deep orange
# Yderligere CSS
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Hjem: index.md
  - Maskiner:
    - maskiner/index.md
    - 3D Printere: maskiner/3dprintere.md
    - Laser: maskiner/laser.md
    - Print & Cut: maskiner/printncut.md
    - CNC: maskiner/cnc.md
    - Arcade: maskiner/arcade.md
  - Openlab: openlab.md
  - Precious Plastic:
    - Precious Plastic/index.md
    #- Oversigt: 'Precious Plastic/intro.md'
    - 🛡️ Sikkerhed: Precious Plastic/sikkerhed.md
    # - 🧪 Forsøgslog: 'Precious Plastic/log.md'
    # - 📸 Galleri: 'Precious Plastic/galleri.md'
  - Om: about.md
  - Artikler:
    - articles/index.md
    - Hjemmesiden: articles/website.md

# Plugins (Rettet syntaks til i18n)
plugins:
  - i18n:
      languages:
        - locale: da
          default: true
          name: Dansk
        - locale: en
          name: English
          nav_translations:
            Hjem: Home
            Maskiner: Machines
            Openlab: Openlab
            Precious Plastic: Precious Plastic
            Om: About
            3D Printere: 3D Printers
            Artikler: Articles
            Hjemmesiden: The Website
      fallback_to_default: true
  - search:
      lang: 
        - da
        - en
#  - optimize:
#      enabled: !ENV [CI, false]


extra:
  social:
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/FablabSkanderborg/
