site_name: Fablab Skanderborg
site_url: https://fablab.dahl.sh

# Markdown Extensions (Diagrammer og infobokse)
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - attr_list

theme:
  name: material
  language: da
  logo: assets/fablab-logo-black-on-transparent.png
  features:
    - navigation.instant
    - navigation.footer
    - navigation.tabs
  palette:
    # Automatisk (system)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Skift til lyst tema
      primary: teal
      accent: deep orange
    # Lyst tema
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Skift til mørkt tema
      primary: teal
      accent: deep orange
    # Mørkt tema
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Skift til system standard
      primary: teal
      accent: deep orange

# Plugins (Sprogstyring og søgning)
plugins:
  - search
  - i18n:
      default_language: da
      languages:
        da:
          name: Dansk
          build: true
        en:
          name: English
          build: true
      fallback_to_default: true

# Navigation (Stier til dine filer)
nav:
  - Home: index.md
  - 3D Print: 3d.md
  - Laser: laser.md
  - Precious Plastic:
      - Oversigt: 'Precious Plastic/intro.md'
      # Fjern '#' herunder når du har oprettet de enkelte .md filer:
      # - 🛡️ Sikkerhed: 'Precious Plastic/sikkerhed.md'
      # - 🧪 Forsøgslog: 'Precious Plastic/log.md'
      # - 📸 Galleri: 'Precious Plastic/galleri.md'
  - Om: about.md

extra:
  social:
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/FablabSkanderborg/
